apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - phoenix.qurolvov.dev
    secretName: phoenix-tls
  rules:
  - host: phoenix.qurolvov.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phoenix-research-svc
            port:
              number: 80
